external_components:
  - source:
      type: local
      path: my_components     
    components: [ tuya_termo ]
    refresh: 0s

esphome:
  name: $devicename
  project:
    name: "MOES_BHT002.LibreTiny"
    version: "CB3S"
  comment: "WIFI Termostate Moes BHT-002 (CB3S)"

bk72xx:
  board: cb3s

logger:
    level: ERROR
    baud_rate: 0
    
api:

ota:
  password: !secret ota_pass

captive_portal:
    
#последовательный порт
uart:
  id: uart_bus
  tx_pin: TX1
  rx_pin: RX1
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

time:
  - platform: sntp
    id: sync_time

climate:
  - platform: tuya_termo
    name: Moes Thermostate
    uart_id: uart_bus
    time_id: sync_time
    visual:
      min_temperature: 5
      max_temperature: 35
      eco_temperature: 20
      overheat_temperature: 45
      deadzone_temperature: 1
    internal_temperature:
      name: Internal Temperature
    external_temperature:
      name: External Temperature
    children_lock:
      name: Child Lock
    shedule_selector:
      name: Plan Period Selector
    shedule_hours:
      name: Plan Hours
    shedule_minutes:
      name: Plan Minutes
    shedule_temperature:
      name: Plan Temperatures
    product_id:   
      name: Product Identifier
